### ISSUE TITLE
Does this plugin enable Internet Explorer testing?

### ISSUE THREAD

**Issue by lrobeson** [Saulis/gemini-browserstack#1]
I'm not clear how exactly to use this plugin, but it sounds like it may enable IE testing since Browserstack has numerous IE options. Any basic config/use cases you could share?

**Comment by Saulis** [comment]
Hi there!

You're on the right tracks, `gemini-browserstack` is meant for running tests using BrowserStack services. It basically handles two jobs: it fires up browser sessions in BS and opens up a tunnel so that they can access web servers on your local network.

From the top of my head, a minimal configuration could look something like this:

``` yml
rootUrl = 'http://localhost:8080/website-under-test'
gridUrl = 'http://any.url/will-be-replaced/by-plugin'

system:
  plugins:
    browserstack:
      username: 'foo'
      accessKey: 'bar'

browsers:
  ie11:
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
```

The available `desiredCapabilities` can be seen in the [BrowserStack Docs](https://www.browserstack.com/automate/capabilities)

Disclaimer: as far as I know, the current version of `gemini-browserstack` doesn't work with the `gemini` v1.0.0 or later - it needs a small patch similar to Saulis/gemini-sauce#6

If you happen to have an account to http://www.saucelabs.com you can also check out the plugin for that at http://github.com/Saulis/gemini-sauce which already supports the latest `gemini`
