### ISSUE TITLE
how to connect to browserstack?

### ISSUE THREAD

**Issue by ganlanyuan** [Saulis/gemini-browserstack#3]
.gemini.yml:
```yml
rootUrl: 'http://localhost:8888',

system:
  plugins:
    browserstack:
      username: xxx
      accessKey: xxx
 
browsers:
  ie11:
    desiredCapabilities:
      os: "WINDOWS"
      os_version: "7"
      browserName: "internet explorer"
      version: "11"
 
  chrome43:
    desiredCapabilities:
      os: "WINDOWS"
      os_version: "10"
      browserName: "chrome"
      version: "43"
```
When I run `gemini test`, always get an error:
```
Unable to connect to http://localhost:4444/wd/hub.
```
Does this mean it still try to connect selenium not browserstack?
