### ISSUE TITLE
How to set environmental variables?

### ISSUE THREAD

**Issue by ganlanyuan** [Saulis/gemini-browserstack#4]
In the documentation it says I can set username/accessKey via environmental variables BS_USERNAME/BS_ACCESS_KEY.
Should I set them in `.bash_profile`?
```
export BS_USERNAME="xxx"
export BS_ACCESS_KEY="xxx"
```
If yes, then how should I set the `browserstack` plugin in `.gemini.yml`? Just leave it empty?
```yml
rootUrl: 'http://localhost:8888'

system:
  plugins:
    browserstack:

browsers:
  ie11:
    windowSize: 600x400
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
```
Thanks
